# Kbuild for lock_etcd kernel module
#
#   make -C /lib/modules/$(uname -r)/build M=$(pwd) modules
#
# Requires GFS2 kernel headers (fs/gfs2/) in the kernel source tree.
# On most distributions these are available under:
#   /lib/modules/$(uname -r)/source/fs/gfs2/
#   or /usr/src/linux-headers-$(uname -r)/fs/gfs2/

GFS2_INC := $(srctree)/fs/gfs2

ccflags-y := -I$(src)/../pkg/protocol -I$(GFS2_INC)

obj-m := lock_etcd.o

lock_etcd-y := lock_etcd_main.o \
               lock_etcd_netlink.o \
               lock_etcd_glock.o \
               lock_etcd_mount.o \
               lock_etcd_lock.o
